
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - "5432"
    ports:
      - 5432:5432
    extra_hosts:
    - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  


# docker network create --driver bridge my_network
# docker network list
#docker run --network=my_network --name postgres_container -p 8080:8080 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

                                                                        # -d image_name
